In [1]:
import numpy as np
import pandas as pd
import random as rd

# DATASET EXEMPLO I

In [2]:
tamanho = 20
rd.seed = 42

sx = [rd.sample(['F', 'M'], 1)[0] for _ in range(tamanho)]
idade = [rd.sample(list(range(18, 75)), 1)[0] for _ in range(tamanho)]
classe = [rd.sample(['A', 'B', 'C'], 1)[0] for _ in range(tamanho)]

dic = {'sexo': sx, 'idade': idade, 'classe': classe}

dados = pd.DataFrame(dic)
dados.sample(5)

sexo  idade classe
9     M     69      B
11    M     40      A
0     F     51      B
7     F     73      B
3     F     23      C

# * LABELENCODER

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
tf = LabelEncoder()
tf.fit(dados[['classe']])

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [5]:
resultado = tf.fit_transform(dados[['classe']])
resultado

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 0, 2, 0, 0, 2, 1, 0, 1, 0, 0, 0, 2, 2, 0, 1, 0, 2, 1])

In [6]:
tf.inverse_transform(resultado)

array(['B', 'A', 'A', 'C', 'A', 'A', 'C', 'B', 'A', 'B', 'A', 'A', 'A',
       'C', 'C', 'A', 'B', 'A', 'C', 'B'], dtype=object)

# * ONEHOTENCODER

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
tf = OneHotEncoder()
tf.fit(dados[['classe']])

OneHotEncoder()

In [9]:
resultado = tf.fit_transform(dados[['classe']]).toarray()
resultado

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [10]:
tf.inverse_transform(resultado)

array([['B'],
       ['A'],
       ['A'],
       ['C'],
       ['A'],
       ['A'],
       ['C'],
       ['B'],
       ['A'],
       ['B'],
       ['A'],
       ['A'],
       ['A'],
       ['C'],
       ['C'],
       ['A'],
       ['B'],
       ['A'],
       ['C'],
       ['B']], dtype=object)

# * MINMAXSCALER

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
tf = MinMaxScaler()
tf.fit(dados[['idade']])

MinMaxScaler()

In [17]:
resultado = tf.fit_transform(dados[['idade']])
resultado

array([[0.56],
       [0.14],
       [0.34],
       [0.  ],
       [0.32],
       [0.04],
       [0.72],
       [1.  ],
       [0.98],
       [0.92],
       [0.08],
       [0.34],
       [0.54],
       [0.6 ],
       [0.54],
       [0.6 ],
       [0.66],
       [0.8 ],
       [0.82],
       [0.9 ]])

In [18]:
tf.inverse_transform(resultado)

array([[51.],
       [30.],
       [40.],
       [23.],
       [39.],
       [25.],
       [59.],
       [73.],
       [72.],
       [69.],
       [27.],
       [40.],
       [50.],
       [53.],
       [50.],
       [53.],
       [56.],
       [63.],
       [64.],
       [68.]])

# * STANDARDSCALER

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
tf = StandardScaler()
tf.fit(dados[['idade']])

StandardScaler()

In [21]:
resultado = tf.fit_transform(dados[['idade']])
resultado

array([[ 0.04840347],
       [-1.30689367],
       [-0.66151408],
       [-1.75865938],
       [-0.72605204],
       [-1.62958346],
       [ 0.56470714],
       [ 1.46823856],
       [ 1.4037006 ],
       [ 1.21008673],
       [-1.50050754],
       [-0.66151408],
       [-0.01613449],
       [ 0.17747939],
       [-0.01613449],
       [ 0.17747939],
       [ 0.37109326],
       [ 0.82285897],
       [ 0.88739693],
       [ 1.14554877]])

In [22]:
tf.inverse_transform(resultado)

array([[51.],
       [30.],
       [40.],
       [23.],
       [39.],
       [25.],
       [59.],
       [73.],
       [72.],
       [69.],
       [27.],
       [40.],
       [50.],
       [53.],
       [50.],
       [53.],
       [56.],
       [63.],
       [64.],
       [68.]])

# DATASET EXEMPLO II

In [23]:
dados = pd.DataFrame({'cores':['Amarelo', 'Verde', 'vermelho'], 'formas': ['circulo', 'quadrado', 'triângulo']})
dados

cores     formas
0   Amarelo    circulo
1     Verde   quadrado
2  vermelho  triângulo

# * GET_DUMMIES

In [ ]:
pd.get_dummies(dados)

cores_Amarelo  cores_Verde  cores_vermelho  formas_circulo  \
0              1            0               0               1   
1              0            1               0               0   
2              0            0               1               0   

   formas_quadrado  formas_triângulo  
0                0                 0  
1                1                 0  
2                0                 1

# * ONEHOTENCODER

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [25]:
tf = OneHotEncoder(handle_unknown='ignore', sparse=False)
tf.fit(dados)

OneHotEncoder(handle_unknown='ignore', sparse=False)

In [26]:
tf.categories_

[array(['Amarelo', 'Verde', 'vermelho'], dtype=object),
 array(['circulo', 'quadrado', 'triângulo'], dtype=object)]

In [30]:
resultado = tf.fit_transform(dados)
resultado

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.]])

In [31]:
tf.feature_names_in_

array(['cores', 'formas'], dtype=object)

In [32]:
tf.get_feature_names_out()

array(['cores_Amarelo', 'cores_Verde', 'cores_vermelho', 'formas_circulo',
       'formas_quadrado', 'formas_triângulo'], dtype=object)

In [34]:
tf.inverse_transform(resultado)

array([['Amarelo', 'circulo'],
       ['Verde', 'quadrado'],
       ['vermelho', 'triângulo']], dtype=object)

# * ORDINALENCODER

In [35]:
from sklearn.preprocessing import OrdinalEncoder

In [36]:
tf = OrdinalEncoder()
tf.fit(dados)

OrdinalEncoder()

In [37]:
tf.categories_

[array(['Amarelo', 'Verde', 'vermelho'], dtype=object),
 array(['circulo', 'quadrado', 'triângulo'], dtype=object)]

In [38]:
resultado = tf.fit_transform(dados)
resultado

array([[0., 0.],
       [1., 1.],
       [2., 2.]])

In [39]:
dadosnew = pd.DataFrame(tf.fit_transform(dados), columns=dados.columns)
dadosnew

cores  formas
0    0.0     0.0
1    1.0     1.0
2    2.0     2.0

In [40]:
tf.inverse_transform(dadosnew)

array([['Amarelo', 'circulo'],
       ['Verde', 'quadrado'],
       ['vermelho', 'triângulo']], dtype=object)