In [1]:
import numpy as np
import pandas as pd
import random as rd

# DATASET EXEMPLO I

In [2]:
tamanho = 20
rd.seed = 42

sx = [rd.sample(['F', 'M'], 1)[0] for _ in range(tamanho)]
idade = [rd.sample(list(range(18, 75)), 1)[0] for _ in range(tamanho)]
classe = [rd.sample(['A', 'B', 'C'], 1)[0] for _ in range(tamanho)]

dic = {'sexo': sx, 'idade': idade, 'classe': classe}

dados = pd.DataFrame(dic)
dados.sample(5)

sexo  idade classe
1     M     60      A
8     F     57      B
4     F     39      A
12    F     38      A
10    F     25      B

# * LABELENCODER

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
tf = LabelEncoder()
tf.fit(dados[['classe']])

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [5]:
resultado = tf.fit_transform(dados[['classe']])
resultado

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 0, 0, 0, 0, 2, 1, 1, 2, 1, 1, 0, 1, 0, 2, 2, 0, 1, 2])

In [6]:
tf.inverse_transform(resultado)

array(['B', 'A', 'A', 'A', 'A', 'A', 'C', 'B', 'B', 'C', 'B', 'B', 'A',
       'B', 'A', 'C', 'C', 'A', 'B', 'C'], dtype=object)

# * ONEHOTENCODER

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
tf = OneHotEncoder()
tf.fit(dados[['classe']])

OneHotEncoder()

In [9]:
resultado = tf.fit_transform(dados[['classe']]).toarray()
resultado

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
tf.inverse_transform(resultado)

array([['B'],
       ['A'],
       ['A'],
       ['A'],
       ['A'],
       ['A'],
       ['C'],
       ['B'],
       ['B'],
       ['C'],
       ['B'],
       ['B'],
       ['A'],
       ['B'],
       ['A'],
       ['C'],
       ['C'],
       ['A'],
       ['B'],
       ['C']], dtype=object)

# * MINMAXSCALER

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
tf = MinMaxScaler()
tf.fit(dados[['idade']])

MinMaxScaler()

In [13]:
resultado = tf.fit_transform(dados[['idade']])
resultado

array([[0.58695652],
       [0.76086957],
       [0.15217391],
       [0.23913043],
       [0.30434783],
       [0.04347826],
       [0.2826087 ],
       [0.93478261],
       [0.69565217],
       [0.06521739],
       [0.        ],
       [0.95652174],
       [0.2826087 ],
       [0.08695652],
       [0.89130435],
       [0.39130435],
       [1.        ],
       [0.30434783],
       [0.80434783],
       [0.67391304]])

In [14]:
tf.inverse_transform(resultado)

array([[52.],
       [60.],
       [32.],
       [36.],
       [39.],
       [27.],
       [38.],
       [68.],
       [57.],
       [28.],
       [25.],
       [69.],
       [38.],
       [29.],
       [66.],
       [43.],
       [71.],
       [39.],
       [62.],
       [56.]])

# * STANDARDSCALER

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
tf = StandardScaler()
tf.fit(dados[['idade']])

StandardScaler()

In [17]:
resultado = tf.fit_transform(dados[['idade']])
resultado

array([[ 0.34313909],
       [ 0.8660177 ],
       [-0.96405744],
       [-0.70261813],
       [-0.50653865],
       [-1.29085657],
       [-0.57189848],
       [ 1.38889631],
       [ 0.66993822],
       [-1.22549674],
       [-1.42157622],
       [ 1.45425613],
       [-0.57189848],
       [-1.16013691],
       [ 1.25817665],
       [-0.24509935],
       [ 1.58497578],
       [-0.50653865],
       [ 0.99673735],
       [ 0.60457839]])

In [18]:
tf.inverse_transform(resultado)

array([[52.],
       [60.],
       [32.],
       [36.],
       [39.],
       [27.],
       [38.],
       [68.],
       [57.],
       [28.],
       [25.],
       [69.],
       [38.],
       [29.],
       [66.],
       [43.],
       [71.],
       [39.],
       [62.],
       [56.]])

# DATASET EXEMPLO II

In [19]:
dados = pd.DataFrame({'cores':['Amarelo', 'Verde', 'vermelho'], 'formas': ['circulo', 'quadrado', 'triângulo']})
dados

cores     formas
0   Amarelo    circulo
1     Verde   quadrado
2  vermelho  triângulo

# * GET_DUMMIES

In [20]:
pd.get_dummies(dados)

cores_Amarelo  cores_Verde  ...  formas_quadrado  formas_triângulo
0              1            0  ...                0                 0
1              0            1  ...                1                 0
2              0            0  ...                0                 1

[3 rows x 6 columns]

# * ONEHOTENCODER

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
tf = OneHotEncoder(handle_unknown='ignore', sparse=False)
tf.fit(dados)

OneHotEncoder(handle_unknown='ignore', sparse=False)

In [23]:
tf.categories_

[array(['Amarelo', 'Verde', 'vermelho'], dtype=object),
 array(['circulo', 'quadrado', 'triângulo'], dtype=object)]

In [24]:
resultado = tf.fit_transform(dados)
resultado

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.]])

In [25]:
tf.feature_names_in_

array(['cores', 'formas'], dtype=object)

In [26]:
tf.get_feature_names_out()

array(['cores_Amarelo', 'cores_Verde', 'cores_vermelho', 'formas_circulo',
       'formas_quadrado', 'formas_triângulo'], dtype=object)

In [27]:
dadosnew = pd.DataFrame(resultado, columns=tf.get_feature_names_out())
dadosnew

cores_Amarelo  cores_Verde  ...  formas_quadrado  formas_triângulo
0            1.0          0.0  ...              0.0               0.0
1            0.0          1.0  ...              1.0               0.0
2            0.0          0.0  ...              0.0               1.0

[3 rows x 6 columns]

In [28]:
tf.inverse_transform(dadosnew)

array([['Amarelo', 'circulo'],
       ['Verde', 'quadrado'],
       ['vermelho', 'triângulo']], dtype=object)

# * ORDINALENCODER

In [29]:
from sklearn.preprocessing import OrdinalEncoder

In [30]:
tf = OrdinalEncoder()
tf.fit(dados)

OrdinalEncoder()

In [31]:
tf.categories_

[array(['Amarelo', 'Verde', 'vermelho'], dtype=object),
 array(['circulo', 'quadrado', 'triângulo'], dtype=object)]

In [32]:
resultado = tf.fit_transform(dados)
resultado

array([[0., 0.],
       [1., 1.],
       [2., 2.]])

In [33]:
dadosnew = pd.DataFrame(tf.fit_transform(dados), columns=dados.columns)
dadosnew

cores  formas
0    0.0     0.0
1    1.0     1.0
2    2.0     2.0

In [34]:
tf.inverse_transform(dadosnew)

array([['Amarelo', 'circulo'],
       ['Verde', 'quadrado'],
       ['vermelho', 'triângulo']], dtype=object)